//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class 一般设备台账
    {
        public int 序号 { get; set; }
        public string 设备名称 { get; set; }
        public string 设备状态 { get; set; }
        public string 设备等级 { get; set; }
        public string 内部编号 { get; set; }
        public string 所属分厂 { get; set; }
        public string 规格型号 { get; set; }
        public string 设备安装地址 { get; set; }
        public string 安装单位 { get; set; }
        public string 设备制造单位 { get; set; }
        public string 产品编号 { get; set; }
        public string 始用时间 { get; set; }
        public Nullable<int> 维修次数 { get; set; }
        public Nullable<decimal> 维修经费 { get; set; }
        public string 备注 { get; set; }
    }
}
