//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class 下沙新厂压力容器台账
    {
        public long 序号 { get; set; }
        public string 容器自编号 { get; set; }
        public string 使用登记证 { get; set; }
        public string 注册编号 { get; set; }
        public string 容器名称 { get; set; }
        public string 设备状态 { get; set; }
        public string 型号 { get; set; }
        public string 设计寿命 { get; set; }
        public string 类别 { get; set; }
        public string 设计压力 { get; set; }
        public string 工作压力 { get; set; }
        public string 工作温度 { get; set; }
        public string 介质 { get; set; }
        public string 规格 { get; set; }
        public string 容积 { get; set; }
        public string 材质 { get; set; }
        public string 制造单位 { get; set; }
        public string 制造年月 { get; set; }
        public string 出厂编号 { get; set; }
        public string 使用年月 { get; set; }
        public string 合格证 { get; set; }
        public string 质量证明书 { get; set; }
        public string 竣工图 { get; set; }
        public string 所在部门 { get; set; }
        public string 具体位置 { get; set; }
        public Nullable<System.DateTime> 上次检验日期 { get; set; }
        public string 上次检验报告编号 { get; set; }
        public string 等级 { get; set; }
        public Nullable<System.DateTime> 下次年度检查日期 { get; set; }
        public Nullable<System.DateTime> 下次检验日期 { get; set; }
        public string 备注1 { get; set; }
        public Nullable<System.DateTime> 注册或迁移日期 { get; set; }
        public Nullable<System.DateTime> 停用日期 { get; set; }
        public string 备注2 { get; set; }
    }
}
