//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class 压力管道台帐
    {
        public int 序号 { get; set; }
        public string 项目名称 { get; set; }
        public string 管道名称 { get; set; }
        public string 设备状态 { get; set; }
        public string 管道编号 { get; set; }
        public string 管道起止点 { get; set; }
        public string 设计单位 { get; set; }
        public string 安装单位 { get; set; }
        public Nullable<System.DateTime> 安装年月 { get; set; }
        public Nullable<System.DateTime> 投用年月 { get; set; }
        public string 公称直径mm { get; set; }
        public string 公称壁厚mm { get; set; }
        public string 累计长度km { get; set; }
        public string 压力Mpa { get; set; }
        public string 温度 { get; set; }
        public string 介质 { get; set; }
        public string 允许最高工作压力Mpa { get; set; }
        public string 管道材质 { get; set; }
        public string 焊口数量 { get; set; }
        public string 管道级别 { get; set; }
        public string 安全等级 { get; set; }
        public string 检验评定单位 { get; set; }
        public string 注册代码 { get; set; }
        public Nullable<System.DateTime> 下次检验日期 { get; set; }
        public string 报告编号 { get; set; }
        public string 备注 { get; set; }
    }
}
