//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class 起重设备台帐
    {
        public int 序号 { get; set; }
        public Nullable<System.DateTime> 本次检验日期 { get; set; }
        public Nullable<System.DateTime> 下次检验日期 { get; set; }
        public string 是否已检 { get; set; }
        public string 资料移交 { get; set; }
        public string 移交日期 { get; set; }
        public string 注册代码 { get; set; }
        public string 设备状态 { get; set; }
        public string 设备等级 { get; set; }
        public string 内部编号 { get; set; }
        public string 原 { get; set; }
        public string 检 { get; set; }
        public string 登 { get; set; }
        public string 所属分厂 { get; set; }
        public string 设备使用地点 { get; set; }
        public string 安装单位 { get; set; }
        public string 设备名称 { get; set; }
        public string 规格型号 { get; set; }
        public string 设备制造单位 { get; set; }
        public string 产品编号 { get; set; }
        public string 电动葫芦产品编号 { get; set; }
        public Nullable<System.DateTime> 出厂日期 { get; set; }
        public Nullable<System.DateTime> 始用时间 { get; set; }
        public string 备注 { get; set; }
    }
}
