//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class 锅炉台账
    {
        public int 序号 { get; set; }
        public string 设备编号 { get; set; }
        public string 设备名称 { get; set; }
        public string 设备状态 { get; set; }
        public string 设备注册编号 { get; set; }
        public string 使用等级证编号 { get; set; }
        public Nullable<System.DateTime> 发证日期 { get; set; }
        public string 型号 { get; set; }
        public string 制造单位 { get; set; }
        public string 安装单位 { get; set; }
        public string 额定蒸发量 { get; set; }
        public string 额定蒸汽压力 { get; set; }
        public string 额定蒸汽温度 { get; set; }
        public string 燃烧方式 { get; set; }
        public string 产品编号 { get; set; }
        public Nullable<System.DateTime> 出厂日期 { get; set; }
        public Nullable<System.DateTime> 投用日期 { get; set; }
        public string 累计运行时间 { get; set; }
        public string 内部检验报告编号 { get; set; }
        public Nullable<System.DateTime> 内部年检日期 { get; set; }
        public string 内部检验结论 { get; set; }
        public Nullable<System.DateTime> 下次内部年检日期 { get; set; }
        public string 外部检验报告编号 { get; set; }
        public Nullable<System.DateTime> 外部检验日期 { get; set; }
        public string 外部检验结论 { get; set; }
        public Nullable<System.DateTime> 下次外部检验日期 { get; set; }
    }
}
